- set_fact:
    single_php_domains: "{{ new_wordpress_vhosts | selectattr('php_fpm', 'defined') }}"

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - php-fpm
    - libapache2-mod-fcgid
    - "{{ php_extra_packages }}"

- name: Enable modules
  shell: a2enmod proxy_fcgi setenvif

- name: Enable php-fpm
  shell: "a2enconf php{{ php_version }}-fpm"

- name: Template default pool config
  template:
    src: php-fpm-default.j2
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/default.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm

- name: Template pools for single domains
  template:
    src: php-fpm-single.j2
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/{{ item.slug }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm
  loop: "{{ single_php_domains }}"

# NB Add modifications for extra lines in php.ini to the `php_ini_tweaks` var (see defaults/main.yml)
- name: Nuke lines for idempotency
  lineinfile:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    regexp: "^{{ item | split(' ') | first}}"
    state: absent
  loop: "{{ php_ini_tweaks }}"

- name: Set php_ini_tweaks
  lineinfile:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    regexp: "^{{ item | split(' ') | first}}"
    line: "{{ item }}"
    state: present
  notify: restart php-fpm
  loop: "{{ php_ini_tweaks }}"
###
  
- name: Install php-mysql module
  apt:
    name: "php{{ php_version }}-mysql"

- name: Restart apache
  service:
    name: apache2
    state: restarted