# Role-ifying SFTP chroot. This one requires rsyslog - probably room for improvement there...

- name: Add sftpusers group
  group:
    name: "{{ sftp_chroot_group }}"
    state: present

- name: Add chroot-y stuff at the end of sshd_config
  blockinfile:
    path: /etc/ssh/sshd_config
    backup: yes
    insertafter: EOF
    block: "{{ sftp_chroot_sshd_block }}"

- name: Ensure default sftp line is absent
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "Subsystem sftp /usr/libexec/openssh/sftp-server"
    state: absent
    validate: /usr/sbin/sshd -T -f %s

- name: Add SFTP users
  user:
    name: "{{ item.name }}"
    group: "{{ sftp_chroot_group }}"
    shell: /sbin/nologin
    home: /incoming
  with_items: "{{ sftp_chroot_users }}"

- name: Add SFTP user keys
  authorized_key:
    user: "{{ item.name }}"
    manage_dir: no
    path: "/etc/ssh-pool/{{ item.name }}.pub"
    key: "{{ item.key }}"
    state: present
  with_items: "{{ sftp_chroot_users }}"



- name: Make sure SFTP-chroot root directory is created (!)
  file:
    path: "{{ sftp_chroot_directory }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Create ssh-pool directory to store SFTP users' authorised keys
  file:
    path: /etc/ssh-pool/
    state: directory
    owner: root
    group: root
    mode: 0755

# TODO - actually add peoples' public keys using a loop

# There's probably a better way to do this than stating all the directory names again...

- name: Create SFTP user directories
  file:
    path: "{{ sftp_chroot_directory }}/{{ item.name }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items: "{{ sftp_chroot_users }}"

- name: Create the user's incoming directories
  file:
    path: "{{ sftp_chroot_directory }}/{{ item.name }}/incoming"
    state: directory
    mode: 0755
    owner: "{{ item.name }}"
    group: "{{ sftp_chroot_group }}"
  with_items: "{{ sftp_chroot_users }}"

# Add SFTP chroot logging

- name: Add rsyslog configuration
  template:
    src: rsyslog.sftp.conf.j2
    dest: /etc/rsyslog.d/sftp.conf
    mode: 0755
    owner: root
    group: root

- name: Restart rsyslog to create socket file
  service:
    name: rsyslog
    state: restarted

- name: Add dev directories for users' logs
  file:
    state: directory
    path: "{{ sftp_chroot_directory }}/{{ item.name }}/dev/"
    mode: 0755
    owner: root
    group: root
  with_items: "{{ sftp_chroot_users }}"

- name: Add "log" hard link
  command: ln -f {{ sftp_chroot_directory }}/sftp.log.socket {{ sftp_chroot_directory }}/"{{ item.name }}"/dev/log
  with_items: "{{ sftp_chroot_users  }}"
