- name: Install Remi's PHP + EPEL repo packages
  yum:
    name: "{{ remi_default_packages }}"
    state: present

- name: Use yum-config-manager to enable the correct repo
  shell: "/bin/yum-config-manager --enable {{ remi_repo_name }}"

- name: Install default packages
  package:
    state: present
    name: "{{ remi_default_php_packages }}"


