- name: Add iptables rules
  iptables_raw:
    name: mysql from web host
    state: present
    keep_unmanaged: no
    weight: 50
    rules: |
      -A INPUT -p tcp -s {{ web_host }}/32 --dport 3306 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT 
  tags: iptables

- name: Add iptables rules
  iptables_raw:
    name: "mysql remote IP {{ item }}"
    state: present
    keep_unmanaged: no
    weight: 50
    rules: |
      -A INPUT -p tcp -s {{ item }}/32 --dport 3306 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT 
  loop: "{{ mysql_remote_ips }}"
  when: mysql_remote_ips is defined and mysql_remote_ips
  tags: iptables