- name: Add iptables rules
  iptables_raw:
    name: Allow loopback - related - established - SSH
    state: present
    keep_unmanaged: no
    weight: 10
    rules: |
      -P INPUT ACCEPT
      -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
      -A INPUT -i lo -j ACCEPT
      -A OUTPUT -o lo -j ACCEPT
      -A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
  tags: iptables

- name: Add iptables rules
  iptables_raw:
    name: mysql server rules
    state: present
    keep_unmanaged: no
    weight: 50
    rules: |
      -A INPUT -p tcp -s {{ web_host }}/32 --dport 3306 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT 
  tags: iptables

- name: Add iptables rules
  iptables_raw:
    name: Reject everything else
    state: present
    keep_unmanaged: no
    weight: 90
    rules: |
      -A INPUT -j REJECT --reject-with icmp-host-prohibited
  tags: iptables
