- name: Add iptables rules [web]
  iptables_raw:
    name: web ports
    state: "{{ web_ports | ternary('present', 'absent') }}"
    keep_unmanaged: no
    weight: 50
    rules: -A INPUT -p tcp -m multiport --dports "{{ web_ports|join(",") }}" -j ACCEPT
  tags: iptables