- name: Add primary iptables rules
  iptables_raw:
    name: primary rules
    state: present
    keep_unmanaged: no
    weight: 10
    rules: |
      -P INPUT ACCEPT
      -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
      -A INPUT -i lo -j ACCEPT
      -A OUTPUT -o lo -j ACCEPT
      -A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
  tags: iptables


- name: Add iptables rules [web]
  iptables_raw:
    name: web ports
    state: "{{ web_ports | ternary('present', 'absent') }}"
    keep_unmanaged: no
    weight: 50
    rules: -A INPUT -p tcp -m multiport --dports "{{ web_ports|join(",") }}" -j ACCEPT
  tags: iptables


- name: Add iptables rules [reject everything else]
  iptables_raw:
    name: Reject everything else
    state: present
    keep_unmanaged: no
    weight: 90
    rules: |
      -A INPUT -j REJECT --reject-with icmp-host-prohibited
  tags: iptables
