---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/ports.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache

- name: Enable Apache mods.
  shell: "a2enmod {{ item }}"
  loop: "{{ apache_mods_enabled }}"
  notify: restart apache

- name: Disable Apache mods.
  shell: "a2dismod {{ item }}"
  with_items: "{{ apache_mods_disabled }}"
  notify: restart apache

- name: Check whether certificates defined in vhosts exist.
  stat: "path={{ item.certificate_file }}"
  register: apache_ssl_certificates
  with_items: "{{ apache_vhosts_ssl }}"

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts

- name: Add apache vhosts configuration [Wordpress] [Old]
  template:
    src: "{{ apache_wordpress_vhosts_template }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_wordpress_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart apache
  when:
    - apache_create_vhosts
    - wordpress_vhosts is defined and wordpress_vhosts
  loop: "{{ wordpress_vhosts }}"

- name: Add apache vhosts configuration [New]
  template:
    src: "{{ apache_new_vhosts_template }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_new_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart apache
  when:
    - apache_create_vhosts
    - new_vhosts is defined and new_vhosts
  loop: "{{ new_new_vhosts }}"

- name: Add New New vhosts configs
  template: 
    src: new-new-vhost.conf.j2
    dest: "{{ apache_conf_path }}/sites-available/{{ item.domain }}.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart apache
  when:
    - apache_create_vhosts
    - new_new_vhosts is defined and new_new_vhosts
  loop: "{{ new_new_vhosts }}"
  tags:
    - new-new-vhosts

# - pause:

# - name: Enable sites
#   shell: a2ensite {{ item.domain }}
#   loop: "{{ new_new_vhosts }}"
#   notify: restart apache

- set_fact:
    dev_prefix: "dev."

# - set_fact:
#     dev_vhosts: "{{ new_vhosts | selectattr('dev', 'defined') | map(attribute='domain') }}"

# - name: Add dev sites
#   template:
#     src: "{{ apache_dev_vhosts_template }}"
#     dest: "{{ apache_conf_path }}/sites-available/{{ apache_dev_vhosts_filename }}"
#     owner: root
#     group: root
#     mode: 0644
#     backup: yes
#   notify: restart apache
#   tags: dev-sites

- name: Add "new" vhost symlink in sites-enabled.
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ item }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ item }}"
    state: link
  notify: restart apache
  with_items:
    - "{{ apache_new_vhosts_filename }}"
  when: apache_create_vhosts
    - apache_create_vhosts
    - new_vhosts is defined and new_vhosts

- name: Add "wordpress" vhost symlink in sites-enabled.
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ item }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ item }}"
    state: link
  notify: restart apache
  with_items:
    - "{{ apache_wordpress_vhosts_filename }}"
  when:
    - apache_create_vhosts
    - wordpress_vhosts is defined and wordpress_vhosts
  tags:
    - dev-sites

- name: Add "new new" vhost symlinks in sites-enabled.
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ item.domain }}.conf"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ item.domain }}.conf"
    state: link
  notify: restart apache
  loop: "{{ new_new_vhosts }}"
  when:
    - apache_create_vhosts
    - new_new_vhosts is defined and new_new_vhosts

- name: Remove default vhost in sites-enabled.
  file:
    path: "{{ apache_conf_path }}/sites-enabled/{{ apache_default_vhost_filename }}"
    state: absent
  notify: restart apache
  when: apache_remove_default_vhost


# - name: Add New New vhosts configs
#   template: 
#     src: new-new-vhost.conf.j2
#     dest: "{{ apache_conf_path }}/sites-available/{{ item.domain }}.conf"
#     owner: root
#     group: root
#     mode: 0644
#     backup: yes
#   notify: restart apache
#   when:
#     - apache_create_vhosts
#   loop: "{{ new_new_vhosts }}"