---
- debug:
    var: apache_ports_configuration_items
    
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache

- name: create sites directories
  file:
    state: directory
    path: "{{ apache_conf_path }}/{{ item }}"
    owner: root
    group: root
    mode: 0755
  loop: "{{ apache_sites_dirs }}"

- name: Add sites-enabled config path
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    line: "IncludeOptional conf.d/sites-enabled/*.conf"
    state: present
  notify: restart apache

- name: Check whether certificates defined in vhosts exist.
  stat:
    path: "{{ item.certificate_file }}"
  register: apache_ssl_certificates
  with_items: "{{ apache_vhosts_ssl }}"

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts

- name: Add apache vhosts configuration [Wordpress] [Old]
  template:
    src: "{{ apache_wordpress_vhosts_template }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_wordpress_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart apache
  when:
    - apache_create_vhosts
    - wordpress_vhosts is defined and wordpress_vhosts
  loop: "{{ wordpress_vhosts }}"

- name: Add apache vhosts configuration [Wordpress] [New]
  template:
    src: "{{ apache_new_wordpress_centos_7_vhosts_template }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ item.domain }}.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart apache
  when:
    - apache_create_vhosts
    - wordpress_new_vhosts is defined and wordpress_new_vhosts
  loop: "{{ wordpress_new_vhosts }}"

- name: Add apache vhosts configuration [New]
  template:
    src: "{{ apache_new_vhosts_template }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_new_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart apache
  when:
    - apache_create_vhosts
    - new_vhosts is defined and new_vhosts

- name: Add vhost symlink in sites-enabled.
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ item }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ item }}"
    state: link
  notify: restart apache
  when:
    - apache_create_vhosts
    - wordpress_vhosts is defined and wordpress_vhosts
  with_items:
    - "{{ apache_wordpress_vhosts_filename }}"

- name: Add vhost symlink in sites-enabled.
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ item }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ item }}"
    state: link
  notify: restart apache
  when:
    - apache_create_vhosts
    - new_vhosts is defined and new_vhosts
  with_items:
    - "{{ apache_new_vhosts_filename }}"

- name: Add New Wordpress vhost symlinks in sites-enabled
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ item.domain }}.conf"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ item.domain }}.conf"
    state: link
  notify: restart apache
  when:
    - apache_create_vhosts
    - wordpress_new_vhosts is defined and wordpress_new_vhosts
  loop: "{{ wordpress_new_vhosts }}"

- name: Configure mod_deflate
  template:
    src: deflate.conf.j2
    dest: "{{ apache_conf_path }}/deflate.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart apache
  when: apache_gzip is defined and apache_gzip