---

docker_edition: "ce"
docker_channel: ["stable"]
docker_version: ""
docker_state: "present"

docker_compose_version: ""

docker_users: ["{{ ansible_env.SUDO_USER | d('root') }}"]

docker_login_become_user: "{{ docker_users | first | d('root') }}"

docker_registries: []

docker_default_daemon_json: |
  "log-driver": "journald"

docker_daemon_json: ""

docker_daemon_flags:
  - "-H unix://"

docker_daemon_environment: []

docker_systemd_override: ""

docker_cron_jobs_prune_flags: "af"
docker_cron_jobs_prune_schedule: ["0", "0", "*", "*", "0"]
docker_cron_jobs:
  - name: "Docker disk clean up"
    job: "docker system prune -{{ docker_cron_jobs_prune_flags }} > /dev/null 2>&1"
    schedule: "{{ docker_cron_jobs_prune_schedule }}"
    cron_file: "docker-disk-clean-up"
    user: "{{ (docker_users | first) | d('root') }}"

docker_package_dependencies:
  - "apt-transport-https"
  - "ca-certificates"
  - "cron"
  - "gnupg2"
  - "software-properties-common"

docker_architecture_map:
  "x86_64": "amd64"
  "aarch64": "arm64"
  "aarch": "arm64"
  "armhf": "armhf"
  "armv7l": "armhf"

docker_apt_key_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
docker_apt_key_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
docker_apt_repository: >
  deb [arch={{ docker_architecture_map[ansible_architecture] }}]
  https://download.docker.com/linux/{{ ansible_distribution | lower }}
  {{ ansible_distribution_release }} {{ docker_channel | join (' ') }}

docker_pip_dependencies:
  - "gcc"
  - "python3-setuptools"
  - "python3-dev"
  - "python3-pip"
  - "virtualenv"

docker_pip_virtualenv: "/usr/local/lib/docker/virtualenv"

docker_default_pip_packages:
  - name: "docker"
    state: "{{ docker_pip_docker_state }}"
  - name: "docker-compose"
    version: "{{ docker_compose_version }}"
    path: "/usr/local/bin/docker-compose"
    src: "{{ docker_pip_virtualenv + '/bin/docker-compose' }}"
    state: "{{ docker_pip_docker_compose_state }}"
docker_pip_packages: []

docker_pip_docker_state: "present"
docker_pip_docker_compose_state: "present"
