- template:
    src: ../templates/netdata.conf.j2
    dest: /etc/netdata/netdata.conf
    owner: root
    group: root
    mode: u=wrx,g=rx,o=r,+x
    backup: yes
  notify: Restart Netdata
  tags: configure
