- name: Install netdata packagecloud key
  apt_key:
    url: "{{ netdata_package_gpg_url }}"
    state: present

- name: Add the netdata package repo
  apt_repository:
    repo: "{{ netdata_debian_repo }}"
    state: present
    filename: netdata

- name: Install the package
  apt:
    name: netdata
    state: present
    update_cache: yes

- name: Create the necessary dir
  file:
    state: directory
    recurse: yes
    path: /etc/netdata/conf.d 

- name: Add the netdata.conf pointer file
  template:
    src: debian-netdata.conf.j2
    dest: /etc/netdata/conf.d/netdata-debian.conf
    owner: root
    group: root
    mode: 0644

