# TODO - do the DB stuff beforehand and take this out as it's mixing DB and web stuff
- name: Set DB name
  set_fact:
    db_name: "{{ item.db_name }}"


- name: Set DB user when db_user is defined
  set_fact:
    db_user: "{{ item.db_user }}"
  tags: passwords
