# TODO - do the DB stuff beforehand and take this out as it's mixing DB and web stuff
# Set facts here only, then handoff to another list of tasks to actually do stuff!!!

### DB password credstash stuff
- name: Set DB name
  set_fact:
    db_name: "{{ item.slug }}_db"

- name: Set DB user
  set_fact:
    db_user: "{{ item.slug }}_db_user"
  tags: passwords

