- include_tasks: db-install-generic.yml
  when: item.db_name is not defined

- include_tasks: db-install-named.yml
  when: item.db_name is defined

#- include_tasks: db-install-subdirs.yml
  #loop: "{{ subdirs_list }}"
  #loop_control:
    #loop_var: subdir_loop
  #when: subdirs_list is defined and subdirs_list

- include_tasks: db-install-tasks.yml


