- include_tasks: db-install-generic.yml
  when: item.db_name is not defined

- include_tasks: db-install-named.yml
  when: item.db_name is defined

- set_fact:
    subdirs_list: "{{ item.subdirs }}"
  when: item.subdirs is defined and item.subdirs

- include_tasks: db-install-subdirs.yml
  with_items: "{{ subdirs_list }}"
  when: item.subdirs is defined and item.subdirs
