# TODO - change the permissions of the WP install at the end - simple 0755 for dirs an 0644 for files
# TODO - Make DB user support a more clever way of specifying - e.g. we're getting different envs with the same password

- include_tasks: db-loop.yml
  with_items: "{{ wordpress_vhosts }}"
  when:
    - "'db' in group_names"
    - wordpress_vhosts is defined and wordpress_vhosts
  tags: db

- include_tasks: db-loop.yml
  with_items: "{{ new_wordpress_vhosts }}"
  when:
    - "'db' in group_names"
    - new_wordpress_vhosts is defined and new_wordpress_vhosts
  tags: db

- include_tasks: db-loop.yml
  with_items: "{{ wordpress_subdirs }}"
  when:
    - "'db' in group_names"
    - wordpress_subdirs is defined and wordpress_subdirs
  
  tags: db

- include_tasks: web-pre.yml
  when: "'web' in group_names"

- debug:
    var: wordpress_path

#- pause:

- include_tasks: web-vhosts-loop.yml
  with_items: "{{ wordpress_vhosts }}"
  when:
    - "'web' in group_names"
    - wordpress_vhosts is defined and wordpress_vhosts

- include_tasks: web-vhosts-loop.yml
  with_items: "{{ new_wordpress_vhosts }}"
  when:
    - "'web' in group_names"
    - new_wordpress_vhosts is defined and new_wordpress_vhosts


- include_tasks: web-subdirs-loop.yml
  with_items: "{{ wordpress_subdirs }}"
  when: 
    - "'web' in group_names"
    - wordpress_subdirs is defined and wordpress_subdirs

- include_tasks: web-post.yml
  when: "'web' in group_names"

