- include_tasks: db-loop.yml
  with_items: "{{ wordpress_vhosts }}"
  when: "'db' in group_names"
  tags: db

- include_tasks: db-loop.yml
  with_items: "{{ wordpress_subdirs }}"
  when:
    - "'db' in group_names"
    - wordpress_subdirs is defined and wordpress_subdirs
  
  tags: db

- include_tasks: web-pre.yml
  when: "'web' in group_names"

- debug:
    var: wordpress_vhosts

- debug:
    var: wordpress_path

#- pause:

- include_tasks: web-vhosts-loop.yml
  with_items: "{{ wordpress_vhosts }}"
  when: "'web' in group_names"

- include_tasks: web-subdirs-loop.yml
  with_items: "{{ wordpress_subdirs }}"
  when: 
    - "'web' in group_names"
    - wordpress_subdirs is defined and wordpress_subdirs

- include_tasks: web-post.yml
  when: "'web' in group_names"

