- debug:
    msg: "slug is {{ item.slug }}"

- debug:
    msg: "dir is {{ item.dir }}"

- debug:
    msg: "table_prefix is {{ item.table_prefix }}"

- name: Concantenate the install and directory into a single variable
  set_fact:
    wordpress_path: "{{wp_install_path}}/{{item.slug}}/httpdocs"

- include_tasks: wp-install.yml
