- name: Construct the path for a subdir install
  set_fact:
    wordpress_path: "{{wp_install_path}}/{{ item.slug }}/httpdocs"

- debug:
    msg: "*** Running web-subdirs-loop for {{ item.slug }} (parent {{ item.parent }}) ***"

- include_tasks: wp-install.yml

- debug:
    msg: "*** End of web-subdirs-loop for {{ item.slug }} (parent {{ item.parent }}) ***"
