- name: Construct the path for a standard vhost
  set_fact:
    wordpress_path: "{{wp_install_path}}/{{item.domain}}/httpdocs"

- debug:
    msg: "*** Running web-vhosts-loop for {{ item.domain }} ***"

- include_tasks: wp-install.yml

- debug:
    msg: "*** End of web-vhosts-loop for {{ item.domain }} ***"
