
- debug:
    var: restic_b2_account_id

- set_fact:
    restic_password: "{{ lookup('password', '/dev/null length=32') }}"

- name: Init the repo, ignore error if it already exists
  shell: "{{ restic_bindir }}/restic -r {{ restic_repo }} init --password-command='echo {{ restic_password }}'"
  environment: "{{ restic_env }}"
  register: repo_init
  ignore_errors: true

- name: Template the restic env var config file
  template:
    src: restic-env.j2
    dest: "{{ restic_env_file }}"
    #owner: root
    #group: root
    mode: 0400
  when: repo_init.rc == 0

- name: Create restic cache dir
  file:
    state: directory
    recurse: yes
    path: "{{ restic_cache_dir }}"
    owner: root
    group: root
    mode: 0644

- name: Create restic-excludes file
  template:
    src: restic-excludes.txt.j2
    dest: "{{ restic_excludes_file }}"
    mode: 0755


    

#TODO:
##- name: See if we have a password in credstash
## Create cron script with relevant backup config(s)

