- include_vars: b2.yml
  when: restic_backend == 'backblaze'

- include_vars: s3.yml
  when: restic_backend == 's3'

- include_tasks: init.yml
  when: restic_repo_init is defined and restic_repo_init

- include_tasks: existing.yml
  when: restic_existing_repos is defined and restic_existing_repos
  loop: "{{ restic_existing_repos }}"

- include: cron.yml
  when: restic_cron is defined and restic_cron
