---
- name: Configure uchiwa dashboard
  template: src=uchiwa.json.j2 dest=/etc/sensu/conf.d/uchiwa.json
  notify: restart sensu-server

- name: Ensure uchiwa is started
  service: name=uchiwa state=started enabled=yes
