# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}.yml"
   - "default.yml"

- name: ensure mysql is running and starts on boot
  service: name={{ mysql_service }} state=started enabled=true

- name: update mysql root password for all root accounts
  mysql_user: name={{ root_db_user }} host=localhost password={{ root_db_password }}

- name: copy .my.cnf file with root password credentials
  template: src=root.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
  - localhost
  - "{{ inventory_hostname }}"

- name: update mysql root password for all root accounts
  mysql_user: name={{ root_db_user }} host={{ item }} password={{ root_db_password }}
  with_items:
  - "{{ ansible_hostname }}"
  - 127.0.0.1
  - ::1
  - localhost

- name: remove the test database
  mysql_db: name=test state=absent

- name: Touch a file for idempotency
  file: path=/etc/mysql.installed owner=root group=root mode=0600 state=touch
