---
- name: Download the given release
  get_url:
    url: "{{ papertrail_remote_syslog_url }}"
    dest: "{{ papertrail_remote_syslog_local }}"
    owner: root
    group: root
    mode: 0644

- name: Install remote_syslog2
  package:
    name: "{{ papertrail_remote_syslog_local }}"
    state: present

- name: Put the config file in place
  template:
    src: remote_syslog2.yml.j2
    dest: /etc/remote-syslog2.yml 

- name: Template the systemd unit
  template:
    src: remote_syslog2.systemd
    dest: /etc/systemd/system/remote_syslog2.service
    mode: 0644
    owner: root
    group: root
  notify: daemon reload
