---
- name: Include pesky OS-specific vars
  include_vars: "{{ item }}"
  with_items:
     - "{{ ansible_os_family }}.yml"

- name: Debug login_users
  debug:
    var: login_users

- name: Add user(s)!
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    groups: "{{ item.groups | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    create_home: "{{ item.create_home | default('no') }}"
  with_items: "{{ login_users }}"

- name: Create home dirs if necessary
  user:
    name: "{{ item.name }}"
    create_home: "{{ item.create_home | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
  with_items: "{{ login_users }}"

- name: Add SSH key if needed
  user:
    name: "{{ item.name }}"
    generate_ssh_key: "{{ item.gen_ssh | default(omit) }}"
    ssh_key_bits: "4096"
  with_items: "{{ login_users }}"
  register: ssh_key_data

- debug:
    var: ssh_key_data

- name: Add authorized keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', 'files/'+ item.name + '.key.pub') }}"
  with_items: "{{ login_users }}"
  ignore_errors: yes

- include_tasks: sudo.yml

- include_tasks: disable.yml
  when: secure_ssh is defined and secure_ssh
