---
- name: Include pesky OS-specific vars
  include_vars: "{{ item }}"
  with_items:
     - "{{ ansible_os_family }}.yml"


- name: Debug login_users
  debug:
    var: login_users

- name: Add user(s)!
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    groups: "{{ item.groups | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
  with_items: "{{ login_users }}"

- name: Add authorized keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', 'files/'+ item.name + '.key.pub') }}"
  with_items: "{{ login_users }}"
  ignore_errors: yes

- include_tasks: sudo.yml

- include_tasks: disable.yml
  when: secure_ssh is defined and secure_ssh
