restic_archive_url: https://github.com/restic/restic/releases/download/v{{ restic_version }}/restic_{{ restic_version }}_linux_amd64.bz2
restic_version: 0.12.0
restic_checksum: 63d13d53834ea8aa4d461f0bfe32a89c70ec47e239b91f029ed10bd88b8f4b80
restic_b2_account_id: "{{  lookup('pipe', 'pass show backblaze/account-id') }}"
restic_b2_application_key: "{{  lookup('pipe', 'pass show backblaze/application-key') }}"
restic_env_file: "~/.restic.cf"
restic_excludes_file: /root/restic-excludes.txt
restic_bindir: /usr/local/sbin
restic_tmp_dir: /var/restic/tmp
restic_cache_dir: /var/restic/cache
restic_initrepo: yes
restic_bucket_name: ticktockhouse-backups
restic_backend: backblaze
restic_repo_init: yes
