remi_php_major_version: 7
remi_php_package: "http://rpms.remirepo.net/enterprise/remi-release-{{ remi_php_major_version }}.rpm"
epel_repo_package: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ remi_php_major_version }}.noarch.rpm"
remi_php_baseurl: "http://rpms.remirepo.net/enterprise/{{ remi_php_major_version }}/{{ remi_php_version }}/$basearch/"
remi_php_packages:
  - {{ remi_php_version }}-php-common
  - {{ remi_php_version }}-php-fpm
remi_default_packages:
  - "{{ epel_repo_package }}"
  - "{{ remi_php_package }}"
  - yum-utils
