---
- name: Copy apache-wp-login.conf
  copy: src=apache-wp-login.conf dest=/etc/fail2ban/filter.d/apache-wp-login.conf mode=0644

- name: Copy and populate jail.local
  template: src=jail.local.j2 dest=/etc/fail2ban/jail.local
  notify:
    - restart fail2ban
  tags: configfiles

- name: Ensure log file is at /var/log/fail2ban.log
  ini_file: dest=/etc/fail2ban/fail2ban.conf section=Definition option=logtarget value=/var/log/fail2ban.log backup=yes 
  notify:
    - restart fail2ban
  tags: logfile
