---
- name: Template fail2ban.conf
  template:
    src: fail2ban.conf.plesk.j2
    dest: /etc/fail2ban/fail2ban.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart fail2ban
  tags: configfiles

- name: Put default jails in place
  template:
    src: default-jails.conf.j2
    dest: /etc/fail2ban/jail.d/default-jails.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
  tags: configfiles

- name: Template default jail.conf
  template:
    src: jail.conf.j2
    dest: /etc/fail2ban/jail.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart fail2ban
  tags: configfiles

- name: Copy extra filters over
  synchronize:
    src: "{{ role_path }}/files/"
    dest: /etc/fail2ban/filter.d/


#- name: Populate defined jails
  #ini_file:

#- name: Copy apache-wp-login.conf
  #copy: src=apache-wp-login.conf dest=/etc/fail2ban/filter.d/apache-wp-login.conf mode=0644

- name: Copy and populate jail.local
  template:
    src: jail.local.j2 
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart fail2ban
  tags: configfiles
