- name: Create prometheus users
  user:
    name: "{{ item }}"
    shell: "/bin/false"
    create_home: no
  with_items:
    "{{ prometheus_users }}"

- name: Create prometheus dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755
  with_items:
    "{{ prometheus_dirs }}"

- name: Download prometheus tarball
  get_url:
    url: "{{ prometheus_download_url }}"
    dest: "{{ prometheus_download_location }}"
    checksum: "sha256:{{ prometheus_sha256sum }}"

- name: Extract said tarball
  unarchive:
    src: "{{ prometheus_download_location }}"
    dest: "/root/"
    remote_src: true

- name: Copy the binaries over
  copy:
    src: /root/{{ prometheus_prefix }}/{{ item }}
    dest: /usr/local/bin/{{ item }}
    owner: prometheus
    group: prometheus
    mode: 0500
    remote_src: true
  with_items: "{{ prometheus_binaries }}"

- name: Copy dirs into place
  synchronize:
    src: "/root/{{ prometheus_prefix }}/{{ item }}"
    dest: "/etc/prometheus/{{ item }}"
  delegate_to: "{{ inventory_hostname }}"
  with_items: "{{ prometheus_console_dirs }}"

- name: Correct the permissions on the dirs
  file:
    dest: /etc/prometheus
    owner: prometheus
    group: prometheus
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: Add prometheus.yml
  template:
    src: readable-prometheus.yml.j2
    # src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0644
    backup: yes
  notify: restart prometheus
  tags: config

- name: Add file_sd files
  template:
    src: file-sd-{{ item }}.yml.j2
    # src: prometheus.yml.j2
    dest: /etc/prometheus/file_sd/{{ item }}.yml
    owner: prometheus
    group: prometheus
    mode: 0644
    backup: yes
  notify: restart prometheus
  loop: 
    - node
  tags: config

- name: Add prometheus systemd unit
  template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  notify: daemon reload

- name: Enable and start prometheus service
  service:
    name: prometheus
    state: started
    enabled: yes
