---
- name: Install munin
  yum: name={{ item }} state=present
  with_items:
    - munin
    - python-passlib
    - py-bcrypt

- include_tasks: plesk.yml

- name: Require basic auth for munin files
  template: src=munin.htaccess.j2 dest={{ munin_files_path }}/.htaccess mode=0644

- name: Add munin htpasswd file
  htpasswd: path="{{ munin_htpasswd_path }}" name="munin" password="{{ munin_htpasswd_password }}" owner=root group=apache mode=0640

- name: Ensure munin-node started
  service: name=munin-node state=started enabled=yes
